version: '3.4'

services:
  happyday.api:
    image: happydayapi
    build:
      context: ../..
      dockerfile: Presentation/HappyDay.Api/Dockerfile
      platforms:
        - linux/amd64
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Container